/**
 * Extends build-trie with utilities that depend upon Node's fs module.
 * 
 * @file with-node-fs
 */
import { readFileSync } from "fs";
import { compileTrieFromWordlist, detectEncodingFromBuffer, enumerateLines, NEWLINE_SEPARATOR } from "./index";
import { WordList, WordListSource, parseWordList } from "../wordlist";

/**
 * Returns a data structure that can be loaded by the TrieModel.
 *
 * It implements a **weighted** trie, whose indices (paths down the trie) are
 * generated by a search key, and not concrete wordforms themselves.
 *
 * @param sourceFiles an array of source files that will be read to generate the trie.
 */
export function createTrieDataStructureFromFilenames(filenames: string[], searchTermToKey: (wf: string) => string): string {
  return compileTrieFromWordlist(wordListFromFilenames(filenames), searchTermToKey);
}

/**
 * Make one big word list out of all of the filenames provided.
 */
function wordListFromFilenames(filenames: string[]) {
  let wordlist: WordList = {};
  filenames.forEach(filename => parseWordListFromFilename(wordlist, filename));
  return wordlist;
}

/**
 * Parses a word list from a file, merging duplicate entries.
 *
 * The word list may be encoded in:
 *
 *  - UTF-8, with or without BOM [exported by most software]
 *  - UTF-16, little endian, with BOM [exported by Microsoft Excel]
 *
 * @param wordlist word list to merge entries into (may have existing entries)
 * @param filename filename of the word list
 */
export function parseWordListFromFilename(wordlist: WordList, filename: string): void {
  parseWordList(wordlist, new WordListFromFilename(filename));
}

/**
 * Given a real filesystem path, this implements the WordList source.
 */
export class WordListFromFilename implements WordListSource {
  readonly name: string;
  constructor(filename: string) {
    this.name = filename;
  }

  *lines() {
    let contents = readFileSync(this.name, detectEncodingFromFilename(this.name));
    yield* enumerateLines(contents.split(NEWLINE_SEPARATOR));
  }
}

function detectEncodingFromFilename(filename: string): 'utf8' | 'utf16le' {
  let buffer = readFileSync(filename);
  return detectEncodingFromBuffer(buffer);
}